[package]
name = "fast_magic_string_sourcemap"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vlq = "0.5.1"
base64 = "0.22.1"
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
