[package]
name = "fms_regexp"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
napi = { workspace = true }
napi-build = { workspace = true }
napi-derive = { workspace = true }
