name: Bench

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: moonrepo/setup-rust@v1

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pnpm bench
          token: ${{ secrets.CODSPEED_TOKEN }}
